from enum import Enum
from typing import List, Literal, Optional

from pydantic import BaseModel, Field, model_validator

from modules.multilingual_support_module import LocalDialectSupportStrategy

class SystemAgents(Enum):
    SET_REMINDERS_ASSISTANT = "set_reminders_assistant"
    GDM_ASSISTANT_AGENT = "gdm-assistant"
    USER_INFO_RETRIEVAL_AGENT = "retrieve-information"
    CDS_ASSISTANT = "cds_assistant"
    VISITOR_ASSISTANT = "visitor-assistant"
    MANAGEMENT_PLAN_ASSISTANT = "management_plan_assistant"
    ISSUES_ASSISTANT = "cds_patient_issues_assistant"


class UserTypes(Enum):
    PATIENT = "patient"
    DOCTOR = "doctor"
    PATIENT_DATA = "patient_data"
    EHR_SYSTEM = "ehr_system"
    TEST_PATIENT = "test_patient"


class Models(Enum):
    LLAMA_3370 = "llama-3.3-70b-versatile"
    LLAMA_3290 = "llama-3.2-90b-vision-preview"
    MIXTRAL_8X7 = "mixtral-8x7b-32768"
    CHATGPT = "gpt-4o-2024-08-06"

class UserPreference(BaseModel):
    user_id: str
    language: str = Field(default=LocalDialectSupportStrategy.ghana_nlp_asr_available_languages["English"])
    modality: str = Field(default="text")
    agent: Optional[str] = None

    @model_validator(mode="after")
    def set_agent(self):
        if self.user_id.startswith('PAT'):
            self.agent = SystemAgents.GDM_ASSISTANT_AGENT.value
        elif self.user_id.startswith('DOC'):
            self.agent = SystemAgents.CDS_ASSISTANT.value
        elif self.user_id.startswith('EHR'):
            self.agent = SystemAgents.ISSUES_ASSISTANT.value
        return self

# @dataclass
# class UserPreference:
#     user_id: str
#     language: str = field(default=LocalDialectSupportStrategy.ghana_nlp_asr_available_languages["English"])
#     modality: str = field(default="text")
#     agent: str = SystemAgents.GDM_ASSISTANT_AGENT.value

class UserAIConversations(BaseModel):
    user_id: str
    conversations: list

# @dataclass
# class UserAIConversations:
#     user_id: str
#     conversations: list

class PatientUpdateIssues(BaseModel):
    """Patient issues and updates for doctor."""
    patient_updates: str = Field(description="Detailed description of any symptoms or complications the pregnant mother is experiencing")
    patient_issues: str = Field(description="updates on pregnancy progress, including test results, fetal behavior, or other relevant observations")

class GDMAssistantResponse(BaseModel):
    """
    A structured response returned by the AI medical assistant.

    This model contains:
    - the regular natural-language response generated by the AI, and
    - a binary escalation flag indicating whether the message contains medically
      concerning information that requires attention from a healthcare professional.

    The purpose is to ensure safe operation in clinical or semi-clinical settings
    by clearly separating conversational output from safety-critical metadata.
    """

    response_text: str = Field(
        ...,
        description=(
            "The AI assistant's natural-language response to the patient's query. "
            "This should address the patient's concerns, provide guidance, or ask "
            "follow-up questions when necessary."
        )
    )

    flag: Literal["normal", "escalate"] = Field(
        ...,
        description=(
            "A binary flag indicating whether the conversation should be escalated "
            "to a medical professional. Use 'normal' for regular conversations and "
            "'escalate' when symptoms or statements suggest a potentially serious "
            "medical issue."
        )
    )

    reason: Optional[str] = Field(
        None,
        description=(
            "An optional explanation describing why the escalation flag was set. "
            "This helps clinicians quickly understand the concern—e.g., 'User "
            "reported chest pain and shortness of breath'. It may be omitted when "
            "flag='normal'."
        )
    )


class Citation(BaseModel):
    source_id: int = Field(
        ...,
        description="The integer ID of a SPECIFIC source which justifies the answer.",
    )
    quote: str = Field(
        ...,
        description="The VERBATIM quote from the specified source that justifies the answer.",
    )

class ClinicalAssessmentResponseStructure(BaseModel):
    """
    Structured output of the model's clinical assessment including impression, plan, and citations.
    """

    impressions: str = Field(
        ...,
        description=(
            "A summary of the clinical impression (suspected diagnosis or assessment of the mother’s and fetus’s condition). "
        )
    )
    plans: str = Field(
        ...,
        description=(
            "The proposed management plan or recommendations, including medications, lifestyle advice, investigations, referrals, or follow-up. "
            "Should be based on the given sources where possible."
        )
    )
    citations: List[Citation] = Field(
        ...,
        description="Citations from the given sources that justify the answer."
    )

class PatientPreferenceRequest(BaseModel):
    phone: str
    language: Literal['en', 'tw']
    modality: Literal['audio', 'text']

class UpdatePIPRequest(BaseModel):
    patient_phone_number: str
    new_management_plan: str
    patient_name: str

class Reminder(BaseModel):
    """
    Represents a reminder configuration for a patient.

    Attributes:
        reminder_text: The message content to be delivered to the patient.
        reminder_time: Signifies the time of day the reminder  would be sent.
            morning = In the morning
            afternoon = In the afternoon
            evening = In the evening
    """
    reminder_text: str
    reminder_time: Literal["morning", "afternoon", "evening"]
    is_active: bool = True

class PatientRemindersResponse(BaseModel):
    """
    Contains all reminders associated with a patient's phone number.

    Attributes:
        patient_phone_number: This should always be None.
        reminders: A list of different reminder entries.
    """
    patient_phone_number: str|None
    reminders: List[Reminder]

class ReminderMessage(BaseModel):
    body: str

class SendReminderRequest(BaseModel):
    recipient_phone_number: str
    reminder: ReminderMessage
